export const GameList = [
  {
    id: 0,
    name: "Imperium",
    gameUrl: "https://www.glisgames.com/SISAL/Imperium/latest/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 1,
    name: "Power Bell",
    gameUrl: "https://www.glisgames.com/SISAL/Powerbell/latest/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 2,
    name: "NasdaX",
    gameUrl: "https://www.glisgames.com/SISAL/NasdaX/dist/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 3,
    name: "Joe Joker Pirate Riches",
    gameUrl: "https://www.glisgames.com/SISAL/JJPirateRiches/latest/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 4,
    name: "Lucky Lobster",
    gameUrl: "https://www.glisgames.com/SISAL/LuckyLobster/dist/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 5,
    name: "Buffalo Gold Rush",
    gameUrl: "https://www.glisgames.com/SISAL/BuffaloGoldRush/dist/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 6,
    name: "Lucky Dynasty",
    gameUrl: "https://www.glisgames.com/SISAL/LuckyDynasty/dist/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 7,
    name: "Stargems",
    gameUrl: "https://www.glisgames.com/SISAL/Stargems/latest/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 8,
    name: "Joe Joker Neon Blast",
    gameUrl: "https://www.glisgames.com/SISAL/NeonJokerBlast/latest/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    id: 9,
    name: "Gate of Cheope",
    gameUrl: "https://www.glisgames.com/SISAL/GOC/STANDALONE/",
    description: "",
    imgUrl: "",
    tags: [],
  },
];
