export const GameList = [
  {
    name: "Imperium",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Power Bell",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "NasdaX",
    gameUrl: "https://www.glisgames.com/SISAL/NasdaX/dist/",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Joe Joker Pirate Riches",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Lucky Lobster",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Buffalo Gold Rush",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Lucky Dynasty",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Stargems",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Joe Joker Neon Blast",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
  {
    name: "Gate of Cheope",
    gameUrl: "",
    description: "",
    imgUrl: "",
    tags: [],
  },
];
